### ISSUE TITLE
Add a Gitlab Template and How-to integrate with ADOP documentation

### ISSUE THREAD

**Issue by bzon** [clerixmaxime/AdopOnOpenshift#9]
To have the flexibility to make use of another Git server instead of locking the users of this platform with Gerrit.  I already have this ready and I can make a Pull Request if permitted.

**Comment by mclerix** [comment]
The goal of this repository is not to hold the migration of ADOP on OpenShift, it is for a demonstration purpose and it should remain this way. However I would be glad if you could contribute to this demonstration and allow the end-user to have the same integrated experience using Gitlab. 
If you have any question on what it implies in the scope of the whole demonstration, don't hesitate to ask.

**Comment by bzon** [comment]
Alright, it's clear now.  I will see how I can contribute by forking this project when it's ready for demo. Thanks!
